# Music Recommendation System

## Data Understanding

In this notebook, I explore the raw Spotify dataset to understand its structure, features, and quality before performing any data cleaning or analysis.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/spotify_tracks.csv")
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

The dataset contains information about Spotify tracks, including song details, artist information, popularity, and audio features.

In [4]:
df.tail()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.640,0.928,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4,world-music

In [5]:
df.shape

(114000, 21)

In [6]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

| Column       | Description                           |
| ------------ | ------------------------------------- |
| track_name   | Name of the song                      |
| artists      | Artist(s)                             |
| album_name   | Album title                           |
| popularity   | Popularity score (0–100)              |
| danceability | How suitable the track is for dancing |
| energy       | Intensity and activity level          |
| valence      | Musical positivity                    |
| tempo        | Speed of the song (BPM)               |

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 26.8 MB

Most audio features are stored as floating-point numbers, while song names and artist names are stored as text.

In [8]:
df.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [9]:
#checking missing values
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [10]:
#checking duplicates 
df.duplicated().sum()

np.int64(0)

In [ ]:
#checking unique values

df["artists"].nunique()

31437

In [14]:
df["track_name"].nunique()

73608

In [16]:
df["track_genre"].nunique()

114

In [15]:
df.sample(10)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
3121,3121,5oJgIQPvytf2nR7WX3vZLn,Weezer,Tek It - New Noise,Records,0,208920,False,0.658,0.773,...,-5.119,1,0.0244,0.000901,0.000000,0.1940,0.660,100.006,4,alternative
67494,67494,0N8d25eR5OMLON40UYIukg,Juanes,tardes tranqui,Dancing In The Dark,1,244680,False,0.629,0.486,...,-8.198,1,0.0305,0.497000,0.000000,0.1170,0.382,122.011,4,latin
6382,6382,2sx2JMObNBuPIrhRp2VfHR,Månegarm,Vredens tid,Segervisa,20,217880,False,0.390,0.286,...,-12.537,1,0.0330,0.841000,0.000000,0.1260,0.363,150.774,3,black-metal
24200,24200,65EjTv04s8iJB5vBcOolqF,Seth Troxler,Lumartes,Lumartes,32,233982,False,0.692,0.625,...,-13.118,0,0.0347,0.017600,0.833000,0.1250,0.199,125.002,4,detroit-techno
35063,35063,3LPUvP4DGq3j0SqBdKWFiN,Zé Vaqueiro;Vitor Fernandes,Vem Me Amar,Vem Me Amar,48,169978,False,0.701,0.745,...,-5.132,1,0.0355,0.334000,0.000000,0.0454,0.870,156.128,4,forro
14439,14439,7sdA0lcpUh8F2EWWevWZD0,The Wiggles,Yummy Yummy,Ponies,33,53466,False,0.787,0.714,...,-8.492,1,0.0490,0.489000,0.006550,0.2200,0.408,129.758,3,children
53266,53266,2MEH84HKs9zYHcA82mVzBy,Zedd;Liam Payne,Fiesta de disfraces vol. II,Get Low,0,204693,False,0.723,0.924,...,-3.518,1,0.0516,0.033200,0.000006,0.0496,0.527,108.009,4,house
30697,30697,2AwTFpFcTm9TyOXqu2OZ8D,Brando;Ninetails,Armada Music - ADE 2022,Saturday Night (Feel The Groove),0,153925,False,0.692,0.775,...,-4.241,0,0.0617,0.027800,0.000000,0.4270,0.634,121.994,4,edm
69436,69436,4uDT6Y5C2WrEFbgla3JmYO,Kester,Hits of Kester (Christian Devotional),Thangum Karangal,30,333600,False,0.338,0.345,...,-11.324,1,0.0469,0.803000,0.000001,0.1350,0.379,189.650,4,malay
48842,48842,3Lf5fr3itZilalJH51cJVZ,De Doelleazen;Zender Obama;R.J. Wielstra;S. Sc...,Wy Jouwe Gas,Titom! Dop2dop (Remix),30,149830,False,0.707,0.966,...,-3.581,1,0.0656,0.005890,0.425000,0.0285,0.715,165.019,4,hardcore

## Summary

The dataset contains Spotify tracks with rich audio features such as danceability, energy, tempo, loudness, and valence.

The dataset appears suitable for building a content-based music recommendation system.

Some duplicate records and missing values were identified, which will be addressed in the next notebook during the data cleaning stage.