# Data Cleaning

## Objective

The objective of this notebook is to clean the raw Spotify dataset by handling missing values, removing duplicate records, standardizing text fields, validating data types, and preparing the dataset for exploratory data analysis and recommendation model development.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/spotify_tracks.csv")
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [3]:
df.shape

(114000, 21)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 26.8 MB

In [5]:
#handling missing values
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [8]:
df["artists"] = df["artists"].fillna("Unknown")
df["album_name"] = df["album_name"].fillna("Unknown")
df["track_name"] = df["track_name"].fillna("Unknown")

In [9]:
#removing duplicates
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [13]:
#removing duplicate songs
df[df.duplicated(subset=["track_name", "artists"])]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
18,2qLMf6TuEC3ruGJg4SMMN6,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,68,189613,False,0.625,0.414,0,-8.700,1,0.0369,0.29400,0.000000,0.1510,0.6690,130.088,4,acoustic
20,3S0OXQeoh0w6AY8WQVckRW,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,75,242946,False,0.703,0.444,11,-9.331,1,0.0417,0.55900,0.000000,0.0973,0.7120,150.960,4,acoustic
22,5TvE3pk05pyFIGdSY9j4DJ,A Great Big World;Christina Aguilera,Is There Anybody Out There? - Track by Track C...,Say Something,70,229400,False,0.407,0.147,2,-8.822,1,0.0355,0.85700,0.000003,0.0913,0.0765,141.284,3,acoustic
28,5QAMZTM5cmLg3fHX9ZbTZi,Jason Mraz,Christmas Time,Winter Wonderland,0,131760,False,0.620,0.309,5,-9.209,1,0.0495,0.78800,0.000000,0.1460,0.6640,145.363,4,acoustic
29,2qESE1ZeWly7I3YjyTXmXh,Jason Mraz,Perfect Christmas Hits,Winter Wonderland,0,131760,False,0.620,0.309,5,-9.209,1,0.0495,0.78800,0.000000,0.1460,0.6640,145.363,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113845,5oyYmgnwGZ74992OLfYD2f,Hillsong Worship;Brooke Ligertwood,Awake,King Of Kings - Live at Hillsong Conference,40,291565,False,0.454,0.427,2,-8.049,1,0.0290,0.02050,0.000000,0.6900,0.1840,135.887,4,world-music
113882,7lYdF3SC4SCJPg5kROvXWx,Bryan & Katie Torwalt,I've Got Good News (Live) [Deluxe],Good News - Live,23,266632,False,0.473,0.474,6,-9.175,1,0.0558,0.39500,0.000000,0.1630,0.2510,140.746,4,world-music
113917,4r0ETFFJMBSQ0Z3ntuMDP2,Hillsong Worship;Mi-kaisha Rose,Never Walk Alone (Live),Never Walk Alone - Live,41,348619,False,0.420,0.553,5,-8.049,1,0.0332,0.14100,0.000000,0.1030,0.2140,143.804,4,world-music
113951,54o7m2sWPTagySKiaPPpT2,Passion;Kristian Stanfill,More Like Jesus (Live),More Like Jesus - Live,44,338694,False,0.404,0.676,10,-5.468,1,0.0354,0.02740,0.000000,0.3520,0.1630,144.056,3,world-music
113991,0CE0Y6GM75cbrqao8EOAlW,Chris Tomlin,The Ultimate Playlist,At The Cross (Love Ran Red),32,250629,False,0.387,0.531,8,-4.788,1,0.0290,0.00305,0.000000,0.2010,0.1530,146.003,4,world-music

In [14]:
df.duplicated(subset=["track_name", "artists"]).sum()

np.int64(32656)

In [15]:
duplicates = df[df.duplicated(subset=["track_name", "artists"], keep=False)]

duplicates.sort_values(by=["track_name", "artists"]).head(20)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
93397,3KKk48f33mlB56F5L5nbJk,Nikolay Kopylov,Popular Opera Arias,"""Don Carlos"" Roderigo'S Death Aria",0,235547,False,0.167,0.332,1,-9.888,1,0.0359,0.99200,0.191000,0.1130,0.0527,62.970,4,romance
93440,3KKk48f33mlB56F5L5nbJk,Nikolay Kopylov,Popular Opera Arias,"""Don Carlos"" Roderigo'S Death Aria",0,235547,False,0.167,0.332,1,-9.888,1,0.0359,0.99200,0.191000,0.1130,0.0527,62.970,4,romance
16385,4yfFraZrNnh2zJTok5fzq7,Felix Mendelssohn;Christopher Herrick;Simon Pr...,Klassische Weihnachtsmusik,"""Hark! The Herald Angels Sing""",0,141000,False,0.158,0.210,7,-16.398,1,0.0330,0.95300,0.860000,0.1530,0.1930,80.984,4,classical
39446,4yfFraZrNnh2zJTok5fzq7,Felix Mendelssohn;Christopher Herrick;Simon Pr...,Klassische Weihnachtsmusik,"""Hark! The Herald Angels Sing""",0,141000,False,0.158,0.210,7,-16.398,1,0.0330,0.95300,0.860000,0.1530,0.1930,80.984,4,german
111315,1Ffxfl1vuEDc0xBVPIQ50s,Kid Koala,"""Was He Slow?"" (Music From The Motion Picture ...","""Was He Slow?"" - Music From The Motion Picture...",37,106880,False,0.754,0.719,10,-5.806,0,0.3710,0.37300,0.259000,0.1200,0.6740,175.990,4,trip-hop
111402,03XMXPAE2Yx6HeqCpAPL5o,Kid Koala,Baby Driver (Music from the Motion Picture),"""Was He Slow?"" - Music From The Motion Picture...",25,106880,False,0.754,0.719,10,-5.806,0,0.3710,0.37300,0.259000,0.1200,0.6740,175.990,4,trip-hop
4152,2Bc4llhjJBW77I552RgA3L,Aphex Twin,Selected Ambient Works Volume II,#3,64,464293,False,0.167,0.071,6,-27.108,0,0.0410,0.91100,0.855000,0.1070,0.0613,143.315,5,ambient
32514,2Bc4llhjJBW77I552RgA3L,Aphex Twin,Selected Ambient Works Volume II,#3,64,464293,False,0.167,0.071,6,-27.108,0,0.0410,0.91100,0.855000,0.1070,0.0613,143.315,5,electronic
61045,7axpJkZcb36Wgjy0SxuEai,≠ME,チョコレートメランコリー<Special Edition>,#おふしょるにっと,33,280693,False,0.516,0.842,8,-1.772,1,0.0309,0.45900,0.000000,0.2060,0.8180,83.933,4,j-idol
63939,7axpJkZcb36Wgjy0SxuEai,≠ME,チョコレートメランコリー<Special Edition>,#おふしょるにっと,33,280693,False,0.516,0.842,8,-1.772,1,0.0309,0.45900,0.000000,0.2060,0.8180,83.933,4,j-rock
15476,3UAcFSrt3b8pVbJ0Z1YGSE,Vluestar,$tars and I feel alone,$tars and I feel alone,59,132858,False,0.567,0.214,0,-18.410,1,0.4440,0.86000,0.000087,0.1200,0.5600,86.251,4,chill
94427,3UAcFSrt3b8pVbJ0Z1YGSE,Vluestar,$tars and I feel alone,$tars and I feel alone,59,132858,False,0.567,0.214,0,-18.410,1,0.4440,0.86000,0.000087,0.1200,0.5600,86.251,4,sad
62864,2MAVcVr2oylw2OZ3hojWYj,The Connells,Ring,'74-'75,67,278973,False,0.530,0.590,11,-9.169,1,0.0250,0.18300,0.002270,0.0675,0.4300,144.202,4,j-pop
63412,2MAVcVr2oylw2OZ3hojWYj,The Connells,Ring,'74-'75,67,278973,False,0.530,0.590,11,-9.169,1,0.0250,0.18300,0.002270,0.0675,0.4300,144.202,4,j-rock
46066,7vNZvwQe1iKA7GriYVXasV,Forze DJ Team,Qlimax 2010 - In An Alternate Reality,'98 To Piano [Mix Cut] - Original Mix,29,41600,False,0.584,0.977,8,-3.418,0,0.0372,0.00333,0.973000,0.2700,0.0375,77.266,4,happy
48913,7vNZvwQe1iKA7GriYVXasV,Forze DJ Team,Qlimax 2010 - In An Alternate Reality,'98 To Piano [Mix Cut] - Original Mix,29,41600,False,0.584,0.977,8,-3.418,0,0.0372,0.00333,0.973000,0.2700,0.0375,77.266,4,hardcore
26778,6PvkgNl39geFWiBMzEeWjM,Nathan Lane;Matthew Broderick;The Producers En...,The Producers (Original Broadway Cast Recording),'Til Him,20,222146,False,0.306,0.205,5,-15.206,1,0.0486,0.93300,0.000006,0.7620,0.2660,82.138,3,disney
98929,6PvkgNl39geFWiBMzEeWjM,Nathan Lane;Matthew Broderick;The Producers En...,The Producers (Original Broadway Cast Recording),'Til Him,20,222146,False,0.306,0.205,5,-15.206,1,0.0486,0.93300,0.000006,0.7620,0.2660,82.138,3,show-tunes
19077,02HqnDssYA62iGapkpJIkJ,Cody Johnson,Country Car Hits,'Til You Can't,1,224213,False,0.501,0.815,1,-4.865,1,0.0436,0.05130,0.000000,0.1060,0.4600,160.087,4,country
19083,0mTSm4MqhfSwCwDnQqABKk,Cody Johnson,Country Road Songs,'Til You Can't,1,224213,False,0.501,0.815,1,-4.865,1,0.0436,0.05130,0.000000,0.1060,0.4600,160.087,4,country

Songs with the same name and artist were inspected. Many belong to different albums, compilations, or versions. Therefore, only exact duplicate rows were removed, while these records were retained.

In [16]:
#removing extra spaces
text_columns = [
    "artists",
    "album_name",
    "track_name",
    "track_genre"
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [17]:
#standardize the genres
df["track_genre"] = df["track_genre"].str.lower()

In [18]:
df.dtypes

track_id                str
artists                 str
album_name              str
track_name              str
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre             str
dtype: object

In [19]:
df.describe()

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [20]:
df["track_genre"].nunique()

114

In [21]:
df["artists"].nunique()

31438

In [22]:
df["track_name"].nunique()

73609

In [23]:
#final validation

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  str
 1   artists           114000 non-null  str
 2   album_name        114000 non-null  str
 3   track_name        114000 non-null  str
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(5), str(5)
memory usage: 25.9 MB

In [24]:
df.isnull().sum()

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(450)

In [27]:
df.to_csv("../data/processed/clean_music.csv", index=False)

## Conclusion

The Spotify dataset was successfully cleaned by:

- Removing unnecessary columns
- Handling missing values
- Removing duplicate rows
- Standardizing text columns
- Validating data types

The cleaned dataset has been saved and is ready for exploratory data analysis.